language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t allesmiguel/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true allesmiguel/docker-react npm run test